image: "fedora:27"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
- dnf -y install gcc gcc-c++ ninja-build git
- dnf -y install cmake openssl-static.i686 glibc-static.i686 libstdc++-static.i686 glibc-devel.i686 openssl-devel.i686 zlib-static.i686
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
- source ~/.cargo/env
- rustup target add i686-unknown-linux-gnu

build:csgo:
  stage: build
  script:
  - cd hl2sdk
  - git checkout csgo
  - cd ../
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
  - PKG_CONFIG_ALLOW_CROSS=1 OPENSSL_DIR=/usr ninja
  - mv build/discord.ext.so build/discord.ext.2.csgo.so
  artifacts:
    paths:
    - build/discord.ext.2.csgo.so
  cache:
    paths:
    - rust/target
    - ~/cargo/registry
