image: "fedora:27"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - bundle

build:linux:
  stage: build
  before_script:
  - dnf -y install gcc gcc-c++ ninja-build
  - dnf -y install cmake openssl-static.i686 glibc-static.i686 libstdc++-static.i686 glibc-devel.i686 openssl-devel.i686 zlib-static.i686
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - source ~/.cargo/env
  - rustup target add i686-unknown-linux-gnu
  script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
  - PKG_CONFIG_ALLOW_CROSS=1 OPENSSL_DIR=/usr ninja
  artifacts:
    paths:
    - build/discord.ext.so
  cache:
    paths:
    - rust/target
    - ~/cargo/registry

bundle:linux:
  stage: bundle
  script:
  - cd build
  - mkdir -p csgo/addons/sourcemod/extensions
  - cp discord.ext.so csgo/addons/sourcemod/extensions/
  - tar -cf discord.tar.gz csgo/
  artifacts:
    paths:
    - build/discord.tar.gz
  dependencies:
  - build:linux
