image: "fedora:27"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - bundle

before_script:
- dnf -y install gcc gcc-c++ ninja-build git
- dnf -y install cmake openssl-static.i686 glibc-static.i686 libstdc++-static.i686 glibc-devel.i686 openssl-devel.i686 zlib-static.i686
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
- source ~/.cargo/env
- rustup target add i686-unknown-linux-gnu

build:csgo:
  stage: build
  script:
  - cd hl2sdk
  - git checkout csgo
  - cd ../
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DSDK=csgo ..
  - PKG_CONFIG_ALLOW_CROSS=1 OPENSSL_STATIC=yes OPENSSL_LIB_DIR=/lib OPENSSL_INCLUDE_DIR=/usr/include ninja
  - mv discord.ext.so discord.ext.2.csgo.so
  artifacts:
    paths:
    - build/discord.ext.2.csgo.so
  cache:
    paths:
    - rust/target
    - ~/cargo/registry

build:tf2:
  stage: build
  script:
  - cd hl2sdk
  - git checkout tf2
  - cd ../
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DSDK=tf2 ..
  - PKG_CONFIG_ALLOW_CROSS=1 OPENSSL_STATIC=yes OPENSSL_LIB_DIR=/lib OPENSSL_INCLUDE_DIR=/usr/include ninja
  - mv discord.ext.so discord.ext.2.tf2.so
  artifacts:
    paths:
    - build/discord.ext.2.tf2.so
  cache:
    paths:
    - rust/target
    - ~/cargo/registry

build:css:
  stage: build
  script:
  - cd hl2sdk
  - git checkout css
  - cd ../
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DSDK=css ..
  - PKG_CONFIG_ALLOW_CROSS=1 OPENSSL_STATIC=yes OPENSSL_LIB_DIR=/lib OPENSSL_INCLUDE_DIR=/usr/include ninja
  - mv discord.ext.so discord.ext.2.css.so
  artifacts:
    paths:
    - build/discord.ext.2.css.so
  cache:
    paths:
    - rust/target
    - ~/cargo/registry

build:insurgency:
  stage: build
  script:
  - cd hl2sdk
  - git checkout insurgency
  - cd ../
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DSDK=insurgency ..
  - PKG_CONFIG_ALLOW_CROSS=1 OPENSSL_STATIC=yes OPENSSL_LIB_DIR=/lib OPENSSL_INCLUDE_DIR=/usr/include ninja
  - mv discord.ext.so discord.ext.2.insurgency.so
  artifacts:
    paths:
    - build/discord.ext.2.insurgency.so
  cache:
    paths:
    - rust/target
    - ~/cargo/registry

bundle:
  stage: bundle
  before_script:
  - echo noop
  script:
  - mkdir -p extensions
  - cp build/*.so extensions/
  artifacts:
    paths:
    - extensions/
    - scripting/