image: Visual Studio 2017
clone_depth: 5

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs
  - cmd: rustup-init.exe --default-host i686-pc-windows-msvc --default-toolchain nightly -y
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - cmd: rustc -Vv
  - cmd: cargo -V

platform: x86
configuration: Release

before_build:
  - cmd: cd hl2sdk
  - cmd: git checkout %SDK%
  - cmd: cd ..
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release -DSDK=%SDK% ..

after_build:
  - cmd: rename Release\discord.ext.dll discord.ext.2.%SDK%.dll
  - cmd: mkdir extensions scripting\include
  - cmd: xcopy /s ..\scripting\include scripting\include
  - cmd: copy Release\discord.ext.2.%SDK%.dll extensions
  - cmd: 7z a discord.zip extensions\ scripting\

build:
  project: build\ALL_BUILD.vcxproj

artifacts:
  - path: build\discord.zip

cache:
  - rust/target
  - C:\Users\appveyor\.cargo\registry