image: Visual Studio 2017
clone_depth: 5

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs
  - cmd: rustup-init.exe --default-host i686-pc-windows-msvc --default-toolchain nightly -y
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - cmd: rustc -Vv
  - cmd: cargo -V

platform: x86
configuration: Release

before_build:
  - cmd: cd hl2sdk
  - cmd: git checkout tf2
  - cmd: cd ..
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..

after_build:
  - cmd: rename Release\discord.ext.dll discord.ext.2.tf2.dll

build:
  project: build\ALL_BUILD.vcxproj

artifacts:
  - path: build\Release\discord.ext.2.tf2.dll

cache:
  - rust/target
  - C:\Users\appveyor\.cargo\registry